# Generated by Django 3.2.5 on 2021-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Endereço de Email')),
                ('fullName', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birthDate', models.DateField(verbose_name='Data de Nascimento')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Telefone')),
                ('document', models.CharField(max_length=255, unique=True, verbose_name='CPF')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
