# Generated by Django 3.2.5 on 2021-07-23 13:47

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
