# Generated by Django 3.2.5 on 2021-07-23 17:26

import account.models
import cpf_field.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(validators=[account.models.calculate_age], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Entre com o formato correto do telefone Ex: (99) 99999-9999', regex='^(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-\\d{4})$')], verbose_name='Telefone'),
        ),
    ]
